name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t vivendas .
      - name: Lint
        run: docker run --rm vivendas npm run lint
      - name: Test
        run: docker run --rm vivendas npm test
